#!/bin/bash

while true; do
  read -p "是否已经导入镜像keepalived:v1.0.0和haproxy:v1.0.0,输入[y/n]: " answer
  case "${answer}" in
    y | Y | yes | YES ) break ;;
    n | N | no | NO ) exit ;;
    *) echo "请输入Y/N" ;;
  esac
done

read -p "请输入用户(回车默认root): " user
user=${user:-root}
echo 用户名: $user
